import { defineConfig, presetUno } from 'unocss'
import { presetAttributify } from '@unocss/preset-attributify'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
  ],
  theme: {
    colors: {
      // Static colors
      'static-black-100': 'var(--static-black-100)',
      'static-black-80': 'var(--static-black-80)',
      'static-black-40': 'var(--static-black-40)',
      'static-black-20': 'var(--static-black-20)',
      'static-black-10': 'var(--static-black-10)',
      'static-black-4': 'var(--static-black-4)',
      'static-white-100': 'var(--static-white-100)',
      'static-white-80': 'var(--static-white-80)',
      'static-white-40': 'var(--static-white-40)',
      'static-white-20': 'var(--static-white-20)',
      'static-white-10': 'var(--static-white-10)',
      'static-white-4': 'var(--static-white-4)',
      // Theme colors
      'black-100': 'var(--black-100)',
      'black-80': 'var(--black-80)',
      'black-40': 'var(--black-40)',
      'black-20': 'var(--black-20)',
      'black-10': 'var(--black-10)',
      'black-4': 'var(--black-4)',
      'white-100': 'var(--white-100)',
      'white-80': 'var(--white-80)',
      'white-40': 'var(--white-40)',
      'white-20': 'var(--white-20)',
      'white-10': 'var(--white-10)',
      'white-4': 'var(--white-4)',
      // Background colors
      'background-1': 'var(--background-1)',
      'background-2': 'var(--background-2)',
      'background-3': 'var(--background-3)',
      'background-4': 'var(--background-4)',
      'background-5': 'var(--background-5)',
      'background-6': 'var(--background-6)',
      // Secondary colors
      'purple': 'var(--secondary-purple)',
      'indigo': 'var(--secondary-indigo)',
      'blue': 'var(--secondary-blue)',
      'cyan': 'var(--secondary-cyan)',
      'mint': 'var(--secondary-mint)',
      'green': 'var(--secondary-green)',
      'yellow': 'var(--secondary-yellow)',
      'orange': 'var(--secondary-orange)',
      'red': 'var(--secondary-red)',
      // Primary & Foreground
      'background': 'var(--background)',
      'foreground': 'var(--foreground)',
      'primary': 'var(--primary)',
      'logo': 'var(--logo)',
      'logo-2': 'var(--logo-2)',
    },
    borderRadius: {
      '0': 'var(--corner-radius-0)',
      '4': 'var(--corner-radius-4)',
      '8': 'var(--corner-radius-8)',
      '12': 'var(--corner-radius-12)',
      '16': 'var(--corner-radius-16)',
      '20': 'var(--corner-radius-20)',
      '24': 'var(--corner-radius-24)',
      '28': 'var(--corner-radius-28)',
      '32': 'var(--corner-radius-32)',
      '40': 'var(--corner-radius-40)',
      '48': 'var(--corner-radius-48)',
      '80': 'var(--corner-radius-80)',
    },
    spacing: {
      '0': 'var(--spacing-0)',
      '4': 'var(--spacing-4)',
      '8': 'var(--spacing-8)',
      '12': 'var(--spacing-12)',
      '16': 'var(--spacing-16)',
      '20': 'var(--spacing-20)',
      '24': 'var(--spacing-24)',
      '28': 'var(--spacing-28)',
      '40': 'var(--spacing-40)',
      '48': 'var(--spacing-48)',
    },
    fontSize: {
      '12': ['var(--font-size-12)', { lineHeight: 'var(--line-height-12)' }],
      '14': ['var(--font-size-14)', { lineHeight: 'var(--line-height-14)' }],
      '16': ['var(--font-size-16)', { lineHeight: 'var(--line-height-16)' }],
      '18': ['var(--font-size-18)', { lineHeight: 'var(--line-height-18)' }],
      '24': ['var(--font-size-24)', { lineHeight: 'var(--line-height-24)' }],
      '32': ['var(--font-size-32)', { lineHeight: 'var(--line-height-32)' }],
      '48': ['var(--font-size-48)', { lineHeight: 'var(--line-height-48)' }],
      '64': ['var(--font-size-64)', { lineHeight: 'var(--line-height-64)' }],
    },
    fontWeight: {
      'regular': 'var(--font-weight-regular)',
      'semibold': 'var(--font-weight-semibold)',
    },
    boxShadow: {
      'glow': 'var(--effect-glow)',
      'focus': 'var(--effect-focus)',
      'inner-shadow': 'var(--effect-inner-shadow)',
      'drop-shadow-1': 'var(--effect-drop-shadow-1)',
      'drop-shadow-2': 'var(--effect-drop-shadow-2)',
      'image-hover': 'var(--effect-image-hover)',
      'glass-1': 'var(--effect-glass-1)',
      'glass-2': 'var(--effect-glass-2)',
    },
    backdropBlur: {
      '40': 'var(--effect-background-blur-40)',
      '100': 'var(--effect-background-blur-100)',
    },
  },
})

